/* Tutorial - 14 - Lazy Loading */

import React from 'react'

const About = () => {
  // var tester = 'test1'
  // var tester1 = 'test2'

  // console.log(tester && tester1)
  return (
    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam interdum nunc sed congue accumsan. Integer imperdiet consequat risus. Etiam justo est, varius a dolor ac, aliquet iaculis nunc. Vestibulum nunc urna, laoreet ac lacus at, tempus congue tellus. Cras feugiat nunc ut ante condimentum, ut varius urna ornare. In egestas turpis id aliquam fermentum. Suspendisse nisl libero, lobortis vel venenatis vitae, pretium ac ligula.

    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras rutrum pellentesque felis, sit amet egestas diam convallis quis. Pellentesque sit amet mi ipsum. Etiam ullamcorper magna tortor, non tincidunt quam molestie a. Morbi eros ante, ornare ut dolor et, dignissim posuere nunc. Duis porttitor metus molestie sollicitudin imperdiet. Donec tincidunt diam ut est pretium eleifend sed vitae lectus. Sed eget pharetra metus, nec tincidunt leo.
    
    Fusce a purus non neque suscipit sollicitudin in semper ex. Nunc et lorem nunc. Integer sit amet nunc consectetur est pellentesque semper id sit amet tortor. Aliquam tellus lorem, cursus eu tempus at, laoreet ut mi. Nunc non elementum nunc. Aliquam condimentum, magna ac dignissim egestas, diam ipsum aliquet purus, non elementum erat tortor at velit. Aliquam id aliquet nisl, nec tincidunt mauris.
    
    Quisque ultricies accumsan nunc, vel lacinia ante tempor ut. Nullam sapien sapien, ullamcorper tempus tortor eu, sagittis elementum quam. Vestibulum ultrices lectus at ex pellentesque consectetur. Aenean volutpat fringilla dolor, nec feugiat nisl interdum eget. Etiam blandit risus a gravida ullamcorper. Quisque ante nibh, tristique id lectus at, tincidunt eleifend velit. Vivamus laoreet arcu vitae lectus ornare, nec hendrerit est sollicitudin. Praesent ac cursus nulla. Ut id sagittis odio. Mauris sed nisi aliquet, ultrices tortor ac, hendrerit justo.
    
    Mauris pretium tristique sapien, a laoreet erat hendrerit sed. Aenean id lorem a arcu rutrum dictum. Donec elementum mauris eget ullamcorper fringilla. Maecenas consectetur nulla at consequat pretium. Integer sit amet nisl felis. Vestibulum eget velit porta, auctor ipsum et, consequat mi. Sed hendrerit erat rhoncus tellus scelerisque tempus vel vel orci. Vivamus at elementum orci. Morbi in turpis ut ante luctus interdum. Proin ut turpis mauris.
    
    Nam dignissim vulputate neque sit amet blandit. Vivamus a tempus leo. Suspendisse commodo ligula nec dolor aliquam, sit amet mattis nisl sollicitudin. Mauris et ligula sit amet arcu sagittis feugiat. Donec ultricies sagittis faucibus. Morbi vitae elit et risus vehicula fringilla. Nunc elementum congue vestibulum. Proin sit amet iaculis est, non rhoncus mi. Maecenas viverra sit amet purus in aliquam. Phasellus vitae sagittis dolor. Fusce felis nisl, consectetur at accumsan sit amet, volutpat et diam. Sed at enim mollis sapien dapibus bibendum. Maecenas est odio, imperdiet et condimentum at, tempor sit amet velit. Fusce lobortis pulvinar condimentum.
    
    Ut non varius arcu. Phasellus dolor massa, ultrices ac justo sed, tincidunt sagittis massa. Nullam non fermentum tellus, ut cursus massa. Integer eget est nulla. Integer in auctor nisi. Nunc tempor scelerisque diam et maximus. Ut luctus vel risus ac accumsan. Pellentesque dictum sit amet justo eu placerat. In quis convallis massa. Sed pulvinar leo eget felis volutpat maximus.
    
    Aliquam erat volutpat. Praesent eu porttitor justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla sed est id quam ultrices luctus. Proin luctus erat id erat porttitor, sit amet dictum lorem facilisis. Aliquam eu ante turpis. Suspendisse sed tincidunt urna, et rutrum nisl. Phasellus vestibulum ante at cursus tincidunt. Maecenas tempor iaculis ipsum quis lobortis. Nullam posuere elit odio, nec feugiat nulla fermentum eget. Nullam faucibus ultricies hendrerit. Vivamus ac ultricies mi.
    
    Nulla sapien ex, rutrum ac lobortis non, porta nec elit. Proin in diam id diam convallis ullamcorper sed sit amet arcu. Duis ut lectus ullamcorper, dapibus metus at, vestibulum ante. Pellentesque vel leo mi. Sed pharetra enim at velit posuere efficitur. Integer euismod lorem a lacus lobortis, mollis bibendum diam malesuada. Vestibulum maximus lobortis rutrum.
    
    Aenean facilisis metus at elit interdum, vel mollis libero finibus. Duis sed ultrices mi. Curabitur ligula nulla, suscipit et dapibus id, faucibus a turpis. Vivamus bibendum massa non efficitur elementum. Vivamus mattis leo massa, vel fringilla tortor mattis a. Nullam sed fringilla tortor. Morbi ac dui varius, mollis lacus id, pharetra eros. Nunc tincidunt mattis elit, a auctor ligula. Curabitur faucibus ligula id nunc molestie, a laoreet nibh condimentum. Maecenas sem ipsum, rhoncus nec mauris vitae, vehicula blandit diam. Nunc eu nulla vitae tellus interdum volutpat. In a porttitor dui.
    
    Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris maximus lacus mi, sit amet fringilla eros mollis vitae. Quisque eget erat quis ligula eleifend auctor eu vel enim. Aliquam venenatis aliquet porttitor. Maecenas arcu nulla, viverra vel massa id, egestas mattis velit. Ut ullamcorper aliquam nibh, ac fermentum est semper at. Suspendisse tincidunt nibh vitae risus tincidunt tempus eu id nunc. Donec et consectetur sapien. Sed euismod nulla rutrum, volutpat ligula eu, feugiat est. Sed sed velit tempus, placerat nisi hendrerit, iaculis sem. Proin ornare posuere mollis. Cras dictum lacus ut lobortis viverra. Morbi ullamcorper imperdiet mauris, eget lobortis enim. Cras a consectetur nisl, a semper magna. Sed tristique enim aliquam, suscipit nunc nec, tincidunt nibh.
    
    Praesent in nunc eget libero lobortis vulputate. Maecenas scelerisque erat eu molestie malesuada. Etiam nec nulla suscipit, tincidunt nunc ut, tempus neque. Donec tincidunt nunc sed lorem porttitor cursus. Morbi erat sapien, feugiat sed convallis vel, varius ut ante. Vestibulum elementum massa condimentum rhoncus tempus. Nulla fermentum tristique volutpat. Donec eget gravida magna, in volutpat nibh. Aliquam egestas congue odio, sit amet laoreet lectus pellentesque vitae. Nunc aliquam tempus libero, feugiat molestie purus facilisis et. Aenean dictum, mi eget sodales dapibus, quam ipsum ornare ipsum, eu rutrum quam ligula id tellus. Donec pellentesque euismod rutrum. Nunc pharetra mauris quis faucibus aliquam. Donec volutpat aliquet neque, ac ultrices ipsum pulvinar eget. Praesent eu elit non leo dapibus rhoncus eu posuere nisl.
    
    Pellentesque imperdiet nulla egestas dignissim interdum. Nulla et nisl tincidunt, gravida risus et, pulvinar est. Donec viverra blandit sapien ut pulvinar. Nunc lacinia erat mollis, blandit nulla vel, lobortis sem. Proin sed porta odio. Nullam id magna ligula. Duis vulputate sagittis elit, vitae congue massa tincidunt ac. Aenean tincidunt, sapien in scelerisque consectetur, nisl orci pharetra massa, eget imperdiet metus arcu quis turpis. Etiam malesuada libero non tristique aliquam. Nunc interdum condimentum mauris, non fringilla urna cursus id.
    
    Nullam vulputate eros et erat volutpat, vitae viverra eros sollicitudin. Sed eu est sollicitudin, vestibulum lectus non, aliquam massa. Donec molestie finibus cursus. In a nisl efficitur, mollis diam nec, finibus ante. Etiam lacus mauris, aliquet sed mi ut, imperdiet pharetra felis. Etiam ultricies massa ut quam condimentum tincidunt. Vestibulum quis dolor et nisl tristique auctor. Donec bibendum magna sed ligula mollis rutrum at accumsan tortor. Sed condimentum, metus non commodo pellentesque, libero ante vestibulum urna, tempus mollis neque magna vel odio. Donec quis velit et velit sollicitudin congue ac ut nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
    
    Aenean condimentum id purus id iaculis. Curabitur tempor ultricies dolor maximus consequat. Ut molestie sagittis dictum. Nullam dui ante, molestie id ante ut, congue porttitor augue. Nullam lacinia tellus ac eros pellentesque lobortis. Nunc pulvinar magna in lacus sodales pretium. Pellentesque tincidunt nisi ac vehicula blandit. Praesent et condimentum urna.
    
    Vivamus ac felis libero. Vestibulum et blandit mi. Suspendisse at nibh id turpis rhoncus convallis. Maecenas vehicula tellus felis, venenatis fermentum sapien lacinia in. Pellentesque pharetra magna quis lectus tempor lacinia. Praesent in eleifend libero, non sollicitudin neque. Phasellus tempor tincidunt metus id ultricies. Nunc quis elit vel nisl vulputate pharetra at at ante.
    
    Donec elementum sem risus, eu eleifend purus egestas et. Donec a leo tristique, egestas purus vitae, tempor nulla. In tincidunt commodo nulla, nec tristique sem iaculis vel. Nunc consectetur euismod vestibulum. Curabitur ornare varius massa. Nunc nulla mauris, euismod non turpis sed, tincidunt dictum justo. Integer accumsan interdum felis. Quisque vestibulum pharetra mauris sed viverra. Proin eget nisl at turpis fringilla hendrerit venenatis a nisi.
    
    Suspendisse potenti. Quisque quis tellus erat. Suspendisse nulla odio, dapibus id malesuada in, euismod sed nisi. Suspendisse eu ligula ut ligula aliquet mattis vitae ut libero. Aliquam erat volutpat. Sed hendrerit mauris sit amet felis euismod, vitae imperdiet risus semper. Quisque et sapien vitae felis congue suscipit ac in eros. In dui ipsum, dignissim a fringilla dictum, congue vitae nisi. Aenean luctus sem at dui lacinia pretium. Proin ut elit tincidunt, venenatis nulla et, ultrices velit. Integer sed turpis non risus facilisis dictum nec sed lacus. Suspendisse vel convallis ligula, vitae sollicitudin orci. Sed vitae auctor massa.
    
    Sed eget tristique mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sapien ante, accumsan non massa vitae, mollis varius turpis. Nulla ultricies scelerisque nisl, eu lobortis ante tempor eget. Nam tincidunt, justo et feugiat dignissim, lectus diam elementum tortor, et finibus elit quam ac turpis. Aliquam nec nunc sit amet ipsum pretium dictum. Curabitur lobortis ante vitae libero convallis, vitae viverra dolor iaculis.
    
    Phasellus dapibus nunc quam, vitae eleifend massa tempus eget. Suspendisse tempus elit nunc. Vivamus nec consectetur dui. Quisque nibh orci, vestibulum id venenatis sit amet, ullamcorper et diam. Vivamus placerat malesuada orci, et congue mi placerat ut. Proin sed interdum nisl. Fusce posuere orci at dolor condimentum interdum. In mollis ultrices tellus sit amet viverra. Fusce condimentum justo ipsum, vel accumsan felis consectetur in. Duis rhoncus tellus vitae tristique imperdiet. Suspendisse scelerisque, est vitae porttitor volutpat, lorem nisi condimentum justo, a ornare sapien purus nec dolor. Phasellus in libero lacinia ipsum laoreet feugiat. Sed et lectus sit amet ligula tincidunt imperdiet. Etiam rutrum gravida mauris in bibendum.</div>
  )
}

export default About
